# Generated by Django 5.0.7 on 2024-08-02 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=50)),
                ('email_id', models.EmailField(max_length=254)),
                ('department', models.CharField(max_length=50)),
                ('dateofjoining', models.DateField()),
                ('status', models.CharField(choices=[('onboarded', 'Onboarded'), ('not_onboarded', 'Not Onboarded')], max_length=20)),
                ('projectdomain', models.CharField(choices=[('sass', 'SaaS'), ('ecommerce', 'E-Commerce'), ('crm', 'CRM'), ('erp', 'ERP'), ('finance', 'Finance')], max_length=20)),
            ],
        ),
    ]
